[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Libraries
lib_deps =
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^3.11.0
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^7.0.0
    adafruit/Adafruit MAX31865 library@^1.6.2

; OTA upload
upload_protocol = espota
upload_port = open-heating.local

; Build flags
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_ARDUHAL_LOG_COLORS=1

; Partition scheme with OTA support + SPIFFS
board_build.partitions = min_spiffs.csv

; Unit test environment
[env:native]
platform = native
test_framework = unity
build_flags = -DUNIT_TEST
